### ISSUE TITLE
Test Lighthouse + web3signer in network gnosis

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodePackage-lighthouse-gnosis#2]
**Test instructions**

You must have at least 2 Gnosis validators.

Install the [web3signer gnosis](https://github.com/dappnode/DAppNodePackage-web3signer-gnosis) and the client [Lighthouse](https://github.com/dappnode/DAppNodePackage-lighthouse-gnosis). You must get the hash from the Github latest release "dot".

In the client use the checkpoint sync feature to be able to start validating in minutes.

The web3signer will listen only to one client, you must select the client Lighthouse at config.

For a deeper test, you may find it useful to check out the grafana dashboards from the client, web3signer, and docker host.

**Test report**

With an editable unique comment report any errors and feedback you may find necessary.

**Testers**
- @pablomendezroyo 
- @3alpha 
- @tropicar 
- @mgarciate

**Comment by tropicar** [comment]
It works for me :heavy_check_mark:

**Comment by tropicar** [comment]
This task its finished.
